using System;
using System.Collections.Generic;

namespace TrinityDB.World
{
    public partial class QuestTemplate
    {
        public uint Id { get; set; }
        public byte QuestType { get; set; }
        public int QuestLevel { get; set; }
        public int MaxScalingLevel { get; set; }
        public uint QuestPackageId { get; set; }
        public int MinLevel { get; set; }
        public short QuestSortId { get; set; }
        public ushort QuestInfoId { get; set; }
        public byte SuggestedGroupNum { get; set; }
        public uint RewardNextQuest { get; set; }
        public uint RewardXpdifficulty { get; set; }
        public float RewardXpmultiplier { get; set; }
        public int RewardMoney { get; set; }
        public uint RewardMoneyDifficulty { get; set; }
        public float RewardMoneyMultiplier { get; set; }
        public uint RewardBonusMoney { get; set; }
        public uint RewardDisplaySpell1 { get; set; }
        public uint RewardDisplaySpell2 { get; set; }
        public uint RewardDisplaySpell3 { get; set; }
        public uint RewardSpell { get; set; }
        public uint RewardHonor { get; set; }
        public uint RewardKillHonor { get; set; }
        public uint StartItem { get; set; }
        public uint RewardArtifactXpdifficulty { get; set; }
        public float RewardArtifactXpmultiplier { get; set; }
        public uint RewardArtifactCategoryId { get; set; }
        public uint Flags { get; set; }
        public uint FlagsEx { get; set; }
        public uint RewardItem1 { get; set; }
        public uint RewardAmount1 { get; set; }
        public uint RewardItem2 { get; set; }
        public uint RewardAmount2 { get; set; }
        public uint RewardItem3 { get; set; }
        public uint RewardAmount3 { get; set; }
        public uint RewardItem4 { get; set; }
        public uint RewardAmount4 { get; set; }
        public uint ItemDrop1 { get; set; }
        public uint ItemDropQuantity1 { get; set; }
        public uint ItemDrop2 { get; set; }
        public uint ItemDropQuantity2 { get; set; }
        public uint ItemDrop3 { get; set; }
        public uint ItemDropQuantity3 { get; set; }
        public uint ItemDrop4 { get; set; }
        public uint ItemDropQuantity4 { get; set; }
        public uint RewardChoiceItemId1 { get; set; }
        public uint RewardChoiceItemQuantity1 { get; set; }
        public uint RewardChoiceItemDisplayId1 { get; set; }
        public uint RewardChoiceItemId2 { get; set; }
        public uint RewardChoiceItemQuantity2 { get; set; }
        public uint RewardChoiceItemDisplayId2 { get; set; }
        public uint RewardChoiceItemId3 { get; set; }
        public uint RewardChoiceItemQuantity3 { get; set; }
        public uint RewardChoiceItemDisplayId3 { get; set; }
        public uint RewardChoiceItemId4 { get; set; }
        public uint RewardChoiceItemQuantity4 { get; set; }
        public uint RewardChoiceItemDisplayId4 { get; set; }
        public uint RewardChoiceItemId5 { get; set; }
        public uint RewardChoiceItemQuantity5 { get; set; }
        public uint RewardChoiceItemDisplayId5 { get; set; }
        public uint RewardChoiceItemId6 { get; set; }
        public uint RewardChoiceItemQuantity6 { get; set; }
        public uint RewardChoiceItemDisplayId6 { get; set; }
        public uint Poicontinent { get; set; }
        public float Poix { get; set; }
        public float Poiy { get; set; }
        public int Poipriority { get; set; }
        public uint RewardTitle { get; set; }
        public uint RewardArenaPoints { get; set; }
        public uint RewardSkillLineId { get; set; }
        public uint RewardNumSkillUps { get; set; }
        public uint PortraitGiver { get; set; }
        public uint PortraitTurnIn { get; set; }
        public uint RewardFactionId1 { get; set; }
        public int RewardFactionValue1 { get; set; }
        public int RewardFactionOverride1 { get; set; }
        public uint RewardFactionCapIn1 { get; set; }
        public uint RewardFactionId2 { get; set; }
        public int RewardFactionValue2 { get; set; }
        public int RewardFactionOverride2 { get; set; }
        public uint RewardFactionCapIn2 { get; set; }
        public uint RewardFactionId3 { get; set; }
        public int RewardFactionValue3 { get; set; }
        public int RewardFactionOverride3 { get; set; }
        public uint RewardFactionCapIn3 { get; set; }
        public uint RewardFactionId4 { get; set; }
        public int RewardFactionValue4 { get; set; }
        public int RewardFactionOverride4 { get; set; }
        public uint RewardFactionCapIn4 { get; set; }
        public uint RewardFactionId5 { get; set; }
        public int RewardFactionValue5 { get; set; }
        public int RewardFactionOverride5 { get; set; }
        public uint RewardFactionCapIn5 { get; set; }
        public uint RewardFactionFlags { get; set; }
        public uint RewardCurrencyId1 { get; set; }
        public uint RewardCurrencyQty1 { get; set; }
        public uint RewardCurrencyId2 { get; set; }
        public uint RewardCurrencyQty2 { get; set; }
        public uint RewardCurrencyId3 { get; set; }
        public uint RewardCurrencyQty3 { get; set; }
        public uint RewardCurrencyId4 { get; set; }
        public uint RewardCurrencyQty4 { get; set; }
        public uint AcceptedSoundKitId { get; set; }
        public uint CompleteSoundKitId { get; set; }
        public uint AreaGroupId { get; set; }
        public uint TimeAllowed { get; set; }
        public ulong? AllowableRaces { get; set; }
        public uint QuestRewardId { get; set; }
        public int Expansion { get; set; }
        public string LogTitle { get; set; }
        public string LogDescription { get; set; }
        public string QuestDescription { get; set; }
        public string AreaDescription { get; set; }
        public string PortraitGiverText { get; set; }
        public string PortraitGiverName { get; set; }
        public string PortraitTurnInText { get; set; }
        public string PortraitTurnInName { get; set; }
        public string QuestCompletionLog { get; set; }
        public short? VerifiedBuild { get; set; }
    }
}
