using System;
using System.Collections.Generic;

namespace TrinityDB.Hotfixes
{
    public partial class ItemSparse
    {
        public uint Id { get; set; }
        public long AllowableRace { get; set; }
        public string Display { get; set; }
        public string Display1 { get; set; }
        public string Display2 { get; set; }
        public string Display3 { get; set; }
        public string Description { get; set; }
        public int Flags1 { get; set; }
        public int Flags2 { get; set; }
        public int Flags3 { get; set; }
        public int Flags4 { get; set; }
        public float PriceRandomValue { get; set; }
        public float PriceVariance { get; set; }
        public uint VendorStackCount { get; set; }
        public uint BuyPrice { get; set; }
        public uint SellPrice { get; set; }
        public uint RequiredAbility { get; set; }
        public int MaxCount { get; set; }
        public int Stackable { get; set; }
        public int StatPercentEditor1 { get; set; }
        public int StatPercentEditor2 { get; set; }
        public int StatPercentEditor3 { get; set; }
        public int StatPercentEditor4 { get; set; }
        public int StatPercentEditor5 { get; set; }
        public int StatPercentEditor6 { get; set; }
        public int StatPercentEditor7 { get; set; }
        public int StatPercentEditor8 { get; set; }
        public int StatPercentEditor9 { get; set; }
        public int StatPercentEditor10 { get; set; }
        public float StatPercentageOfSocket1 { get; set; }
        public float StatPercentageOfSocket2 { get; set; }
        public float StatPercentageOfSocket3 { get; set; }
        public float StatPercentageOfSocket4 { get; set; }
        public float StatPercentageOfSocket5 { get; set; }
        public float StatPercentageOfSocket6 { get; set; }
        public float StatPercentageOfSocket7 { get; set; }
        public float StatPercentageOfSocket8 { get; set; }
        public float StatPercentageOfSocket9 { get; set; }
        public float StatPercentageOfSocket10 { get; set; }
        public float ItemRange { get; set; }
        public uint BagFamily { get; set; }
        public float QualityModifier { get; set; }
        public uint DurationInInventory { get; set; }
        public float DmgVariance { get; set; }
        public short AllowableClass { get; set; }
        public ushort ItemLevel { get; set; }
        public ushort RequiredSkill { get; set; }
        public ushort RequiredSkillRank { get; set; }
        public ushort MinFactionId { get; set; }
        public short ItemStatValue1 { get; set; }
        public short ItemStatValue2 { get; set; }
        public short ItemStatValue3 { get; set; }
        public short ItemStatValue4 { get; set; }
        public short ItemStatValue5 { get; set; }
        public short ItemStatValue6 { get; set; }
        public short ItemStatValue7 { get; set; }
        public short ItemStatValue8 { get; set; }
        public short ItemStatValue9 { get; set; }
        public short ItemStatValue10 { get; set; }
        public ushort ScalingStatDistributionId { get; set; }
        public ushort ItemDelay { get; set; }
        public ushort PageId { get; set; }
        public ushort StartQuestId { get; set; }
        public ushort LockId { get; set; }
        public ushort RandomSelect { get; set; }
        public ushort ItemRandomSuffixGroupId { get; set; }
        public ushort ItemSet { get; set; }
        public ushort ZoneBound { get; set; }
        public ushort InstanceBound { get; set; }
        public ushort TotemCategoryId { get; set; }
        public ushort SocketMatchEnchantmentId { get; set; }
        public ushort GemProperties { get; set; }
        public ushort LimitCategory { get; set; }
        public ushort RequiredHoliday { get; set; }
        public ushort RequiredTransmogHoliday { get; set; }
        public ushort ItemNameDescriptionId { get; set; }
        public byte OverallQualityId { get; set; }
        public byte InventoryType { get; set; }
        public sbyte RequiredLevel { get; set; }
        public byte RequiredPvprank { get; set; }
        public byte RequiredPvpmedal { get; set; }
        public byte MinReputation { get; set; }
        public byte ContainerSlots { get; set; }
        public sbyte StatModifierBonusStat1 { get; set; }
        public sbyte StatModifierBonusStat2 { get; set; }
        public sbyte StatModifierBonusStat3 { get; set; }
        public sbyte StatModifierBonusStat4 { get; set; }
        public sbyte StatModifierBonusStat5 { get; set; }
        public sbyte StatModifierBonusStat6 { get; set; }
        public sbyte StatModifierBonusStat7 { get; set; }
        public sbyte StatModifierBonusStat8 { get; set; }
        public sbyte StatModifierBonusStat9 { get; set; }
        public sbyte StatModifierBonusStat10 { get; set; }
        public byte DamageDamageType { get; set; }
        public byte Bonding { get; set; }
        public byte LanguageId { get; set; }
        public byte PageMaterialId { get; set; }
        public byte Material { get; set; }
        public byte SheatheType { get; set; }
        public byte SocketType1 { get; set; }
        public byte SocketType2 { get; set; }
        public byte SocketType3 { get; set; }
        public byte SpellWeightCategory { get; set; }
        public byte SpellWeight { get; set; }
        public byte ArtifactId { get; set; }
        public byte ExpansionId { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
