using System;
using System.Collections.Generic;

namespace TrinityDB.Hotfixes
{
    public partial class PlayerCondition
    {
        public long RaceMask { get; set; }
        public string FailureDescription { get; set; }
        public uint Id { get; set; }
        public byte Flags { get; set; }
        public ushort MinLevel { get; set; }
        public ushort MaxLevel { get; set; }
        public int ClassMask { get; set; }
        public sbyte Gender { get; set; }
        public sbyte NativeGender { get; set; }
        public uint SkillLogic { get; set; }
        public byte LanguageId { get; set; }
        public byte MinLanguage { get; set; }
        public int MaxLanguage { get; set; }
        public ushort MaxFactionId { get; set; }
        public byte MaxReputation { get; set; }
        public uint ReputationLogic { get; set; }
        public sbyte CurrentPvpFaction { get; set; }
        public byte MinPvprank { get; set; }
        public byte MaxPvprank { get; set; }
        public byte PvpMedal { get; set; }
        public uint PrevQuestLogic { get; set; }
        public uint CurrQuestLogic { get; set; }
        public uint CurrentCompletedQuestLogic { get; set; }
        public uint SpellLogic { get; set; }
        public uint ItemLogic { get; set; }
        public byte ItemFlags { get; set; }
        public uint AuraSpellLogic { get; set; }
        public ushort WorldStateExpressionId { get; set; }
        public byte WeatherId { get; set; }
        public byte PartyStatus { get; set; }
        public byte LifetimeMaxPvprank { get; set; }
        public uint AchievementLogic { get; set; }
        public uint LfgLogic { get; set; }
        public uint AreaLogic { get; set; }
        public uint CurrencyLogic { get; set; }
        public ushort QuestKillId { get; set; }
        public uint QuestKillLogic { get; set; }
        public sbyte MinExpansionLevel { get; set; }
        public sbyte MaxExpansionLevel { get; set; }
        public sbyte MinExpansionTier { get; set; }
        public sbyte MaxExpansionTier { get; set; }
        public byte MinGuildLevel { get; set; }
        public byte MaxGuildLevel { get; set; }
        public byte PhaseUseFlags { get; set; }
        public ushort PhaseId { get; set; }
        public uint PhaseGroupId { get; set; }
        public int MinAvgItemLevel { get; set; }
        public int MaxAvgItemLevel { get; set; }
        public ushort MinAvgEquippedItemLevel { get; set; }
        public ushort MaxAvgEquippedItemLevel { get; set; }
        public sbyte ChrSpecializationIndex { get; set; }
        public sbyte ChrSpecializationRole { get; set; }
        public sbyte PowerType { get; set; }
        public byte PowerTypeComp { get; set; }
        public byte PowerTypeValue { get; set; }
        public uint ModifierTreeId { get; set; }
        public int WeaponSubclassMask { get; set; }
        public ushort SkillId1 { get; set; }
        public ushort SkillId2 { get; set; }
        public ushort SkillId3 { get; set; }
        public ushort SkillId4 { get; set; }
        public ushort MinSkill1 { get; set; }
        public ushort MinSkill2 { get; set; }
        public ushort MinSkill3 { get; set; }
        public ushort MinSkill4 { get; set; }
        public ushort MaxSkill1 { get; set; }
        public ushort MaxSkill2 { get; set; }
        public ushort MaxSkill3 { get; set; }
        public ushort MaxSkill4 { get; set; }
        public uint MinFactionId1 { get; set; }
        public uint MinFactionId2 { get; set; }
        public uint MinFactionId3 { get; set; }
        public byte MinReputation1 { get; set; }
        public byte MinReputation2 { get; set; }
        public byte MinReputation3 { get; set; }
        public ushort PrevQuestId1 { get; set; }
        public ushort PrevQuestId2 { get; set; }
        public ushort PrevQuestId3 { get; set; }
        public ushort PrevQuestId4 { get; set; }
        public ushort CurrQuestId1 { get; set; }
        public ushort CurrQuestId2 { get; set; }
        public ushort CurrQuestId3 { get; set; }
        public ushort CurrQuestId4 { get; set; }
        public ushort CurrentCompletedQuestId1 { get; set; }
        public ushort CurrentCompletedQuestId2 { get; set; }
        public ushort CurrentCompletedQuestId3 { get; set; }
        public ushort CurrentCompletedQuestId4 { get; set; }
        public int SpellId1 { get; set; }
        public int SpellId2 { get; set; }
        public int SpellId3 { get; set; }
        public int SpellId4 { get; set; }
        public int ItemId1 { get; set; }
        public int ItemId2 { get; set; }
        public int ItemId3 { get; set; }
        public int ItemId4 { get; set; }
        public uint ItemCount1 { get; set; }
        public uint ItemCount2 { get; set; }
        public uint ItemCount3 { get; set; }
        public uint ItemCount4 { get; set; }
        public ushort Explored1 { get; set; }
        public ushort Explored2 { get; set; }
        public uint Time1 { get; set; }
        public uint Time2 { get; set; }
        public int AuraSpellId1 { get; set; }
        public int AuraSpellId2 { get; set; }
        public int AuraSpellId3 { get; set; }
        public int AuraSpellId4 { get; set; }
        public byte AuraStacks1 { get; set; }
        public byte AuraStacks2 { get; set; }
        public byte AuraStacks3 { get; set; }
        public byte AuraStacks4 { get; set; }
        public ushort Achievement1 { get; set; }
        public ushort Achievement2 { get; set; }
        public ushort Achievement3 { get; set; }
        public ushort Achievement4 { get; set; }
        public byte LfgStatus1 { get; set; }
        public byte LfgStatus2 { get; set; }
        public byte LfgStatus3 { get; set; }
        public byte LfgStatus4 { get; set; }
        public byte LfgCompare1 { get; set; }
        public byte LfgCompare2 { get; set; }
        public byte LfgCompare3 { get; set; }
        public byte LfgCompare4 { get; set; }
        public uint LfgValue1 { get; set; }
        public uint LfgValue2 { get; set; }
        public uint LfgValue3 { get; set; }
        public uint LfgValue4 { get; set; }
        public ushort AreaId1 { get; set; }
        public ushort AreaId2 { get; set; }
        public ushort AreaId3 { get; set; }
        public ushort AreaId4 { get; set; }
        public uint CurrencyId1 { get; set; }
        public uint CurrencyId2 { get; set; }
        public uint CurrencyId3 { get; set; }
        public uint CurrencyId4 { get; set; }
        public uint CurrencyCount1 { get; set; }
        public uint CurrencyCount2 { get; set; }
        public uint CurrencyCount3 { get; set; }
        public uint CurrencyCount4 { get; set; }
        public uint QuestKillMonster1 { get; set; }
        public uint QuestKillMonster2 { get; set; }
        public uint QuestKillMonster3 { get; set; }
        public uint QuestKillMonster4 { get; set; }
        public uint QuestKillMonster5 { get; set; }
        public uint QuestKillMonster6 { get; set; }
        public int MovementFlags1 { get; set; }
        public int MovementFlags2 { get; set; }
        public short VerifiedBuild { get; set; }
    }
}
